config/routes.rb
Rails.application.routes.draw do
  resources :recurring_events
  resources :events
  resources :food_journals
  resources :users, only: [:new, :create]
  resource :sessions, only: [:new, :destroy, :create]
  root 'visitors#index'
end

app/models/food_journal.rb
class FoodJournal < ApplicationRecord
    belongs_to :user, optional: true
    has_many :taggings, dependent: :destroy
    has_many :tags, through: :taggings

    mount_uploader :image, ImageUploader

    validates :title, presence: true
    validates :description, presence: true
    validates :before_sugar_lvl , presence: true
    validates :after_sugar_lvl, presence: true

    def tag_names
        self.tags.map{ |t| t.name }.join(",")
      end
    
       # Appending = at the end of a method name, allows to implement
      # a "setter". A setter is a method that is assignable.
      # Example:
      # p.tag_names = "stuff,yo"
      # The code in the example above would call the method we wrote
      # below where the value on the right-hand side of the = would
      # become the argument to the method.
      # This is similar to implementing an `attr_writer`.
      def tag_names=(rhs)
        self.tags = rhs.strip.split(/\s*,\s*/).map do |tag_name|
          Tag.find_or_initialize_by(name: tag_name)
        end
      end

end

app/controllers/food_journals_controller.rb
class FoodJournalsController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]
    before_action :find_product, only: [:show, :edit, :update, :destroy]
    before_action :authorize!, only: [:edit, :update, :destroy]
    def new 
        @foodJournal = FoodJournal.new
    end

    def create

        @foodJournal = FoodJournal.new foodJournal_params
        @foodJournal.user = current_user
        
        if @foodJournal.save
            flash[:notice] = "Food Journal created successfully"
           
            redirect_to food_journal_path(@foodJournal)
          else
            
            render :new
          end

    end

    def show

    end

    
    def index

        @foodJournal = FoodJournal.all

    end


    def edit
        
    end


    def update 

       

        if @foodJournal.update foodJournal_params
            redirect_to food_journal_path(@foodJournal)
          else
            render :edit
          end
    end


    def destroy



        @foodJournal.destroy
        redirect_to food_journals_path
    end


    private

    


    def foodJournal_params

        params.require(:food_journal).permit(:title, :description, :before_sugar_lvl, :after_sugar_lvl, :tag_names, :image)


    end

    def find_product
         @foodJournal = FoodJournal.find params[:id]
    end

    def authorize!
        redirect_to food_journal_path, alert: "access denied" unless can?(:crud, @foodJournal)
      end
end

app/helpers/food_journals_helper.rb
module FoodJournalsHelper
end

app/views/food_journals/edit.html.erb
<h1>New Food Journal Entry</h1>

<% if @foodJournal.errors.any? %>
  <ul>
    <% @foodJournal.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>


<%= form_for @foodJournal do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
    <div>
    <%= f.file_field :image %>
  </div>
   <div>
    <%= f.label :before_sugar_lvl %>
    <%= f.text_field :before_sugar_lvl %>
  </div> <div>
    <%= f.label :after_sugar_lvl %>
    <%= f.text_field :after_sugar_lvl %>
  </div>
  <%= f.submit %>
<% end %>

app/views/food_journals/index.html.erb
<h1>All Food Journals</h1>
<h2><%= link_to "New Entry", new_food_journal_path %></h2>
<% @foodJournal.each do |fj|  %>
  <div>
    <h3><%= link_to fj.title, food_journal_path(fj) %></h3>
    <%= image_tag(fj.image_url.to_s) %>
    <p>Description: <%= fj.description %></p>
    <p>Before sugar level: <%= fj.before_sugar_lvl %></p>
    <p>After sugar level: <%= fj.after_sugar_lvl %></p>
    <div>
      <% fj.tags.each do |tag| %>
        <%= tag.name %>
      <% end %>
    </div>
    
    <hr>
  </div>
<% end %>

app/views/food_journals/new.html.erb
<h1>New Food Journal Entry</h1>
<% if @foodJournal.errors.any? %>
  <ul>
    <% @foodJournal.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>




<%= form_for @foodJournal do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
   <div class="form-group">
    <%= f.label :Ingredients %>
    <%= f.text_field :tag_names %>
  </div>
  <div class="form-group">
    <%= f.label :meal_description %>
    <%= f.text_area :description %>
  </div>
   <div class="form-group">
   
    <%= f.label :add_an_image %>

    <%= f.file_field :image %>
  </div>
   <div class="form-group">
    <%= f.label :before_sugar_lvl %>
    <%= f.text_field :before_sugar_lvl %>
  </div> 
  <div class="form-group">
    <%= f.label :after_sugar_lvl %>
    <%= f.text_field :after_sugar_lvl %>
  </div>
 
  <%= f.submit class: 'btn btn-primary' %>
<% end %>



<script>
  // Documentation for selectize.js:
  // https://selectize.github.io/selectize.js/
  // For description of options that are usable go to:
  // https://github.com/selectize/selectize.js/blob/master/docs/usage.md
  $("#food_journal_tag_names").selectize({
    delimiter: ',',
    persist: false,
    labelField: "name",
    valueField: "name",
    searchField: "name",
    options: <%= Tag.select(:name).to_json(except: [:id]).html_safe %>,
    create (input) {
      return { name: input }
    }
  })
</script>

app/views/food_journals/show.html.erb
<h1><%= @foodJournal.title %></h1>

<%= image_tag(@foodJournal.image_url.to_s) %>

<p>Description: <%= @foodJournal.description %></p>

<p>Before sugar level: <%= @foodJournal.before_sugar_lvl %></p>

<p>After sugar level:<%= @foodJournal.after_sugar_lvl %></p>

<p>Created at: <%= @foodJournal.created_at %></p>

<%= link_to "Edit", edit_food_journal_path(@foodJournal) %>
<%= link_to "Delete", food_journal_path(@foodJournal), method: :delete, data: {confirm: "Are you sure"} %>

<hr />


<% unless @foodJournal.tags.empty? %>
  <div>
    <% @foodJournal.tags.each do |tag| %>
      <%= tag.name %>
    <% end %>
  </div>
<% end %>