config/routes.rb
Rails.application.routes.draw do
  resources :recurring_events
  resources :events
  resources :food_journals
  resources :users, only: [:new, :create]
  resource :sessions, only: [:new, :destroy, :create]
  root 'visitors#index'
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
      <%= link_to 'Food Journal', food_journals_path, class: 'navbar-brand' %>
      <a class='navbar-brand'></a>
      <a class='navbar-brand'></a>
      <a class='navbar-brand'></a>
      <a class='navbar-brand'></a>
      <a class='navbar-brand'></a>
      <a class='navbar-brand'></a>
      <a class='navbar-brand'></a>
      <a class='navbar-brand'></a>
      <a class='navbar-brand'></a>
      <a class='navbar-brand'></a>
      <a class='navbar-brand'></a>
      <a class='navbar-brand'></a>
      <a class='navbar-brand'></a>
      <a class='navbar-brand'></a>
      <a class='navbar-brand'></a>
      <a class='navbar-brand'></a>
      <a class='navbar-brand'></a>
      <a class='navbar-brand'></a>
      <a class='navbar-brand'></a>
      <a class='navbar-brand'></a>
      <a class='navbar-brand'></a>
      <a class='navbar-brand'></a>
      <a class='navbar-brand'></a>
      <a class='navbar-brand'></a>
      <a class='navbar-brand'></a>
      <a class='navbar-brand'></a>
      <a class='navbar-brand'></a>
      <a class='navbar-brand'></a>
      <a class='navbar-brand'></a>
      <a class='navbar-brand'></a>
      <a class='navbar-brand'></a>
      <a class='navbar-brand'></a>
      <a class='navbar-brand'></a>
      <a class='navbar-brand'></a>
      <a class='navbar-brand'></a>
      <a class='navbar-brand'></a>
      <a class='navbar-brand'></a>
      <a class='navbar-brand'></a>
      <a class='navbar-brand'></a>
      <a class='navbar-brand'></a>
      <a class='navbar-brand'></a>
      <a class='navbar-brand'></a>
      <a class='navbar-brand'></a>
      <a class='navbar-brand'></a>
      <a class='navbar-brand'></a>
      <a class='navbar-brand'></a>
      <a class='navbar-brand'></a>
      <a class='navbar-brand'></a>
      <a class='navbar-brand'></a>
      <a class='navbar-brand'></a>
      <a class='navbar-brand'></a>
      <a class='navbar-brand'></a>
      <a class='navbar-brand'></a>
      <a class='navbar-brand'></a>
      <a class='navbar-brand'></a>
      <% if user_signed_in? %>
      <a class='navbar-brand'>Hello,<%= current_user.first_name  %></a>
      <%= link_to "Logout", sessions_path, method: :delete, data: {confirm: "are you sure you want to log out?"}, class: 'navbar-brand'%>
      <% else %>
      <%= link_to "Login", new_sessions_path %> |
      <%= link_to "Sign Up", new_user_path %>
      <% end %>

    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Template" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Template" %>">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class="container-fluid">
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
      <div class='container'>
        <%= render 'layouts/messages' %>
        <%= yield %>
        <div id='remote_container'></div>
      </div>
    </main>
  </body>
</html>